feat: closes gh-10 added userGuardians api to redux
Neoplatonist/bog-republic-ts pull request #12
Opened 2022-10-14 12:51 UTC by TofuSupreme

2022-10-14 13:34 UTC, Neoplatonist commented on libs/redux/userGuardians/api.ts
> +      providesTags: ['userGuardiansApi'],
Sorry, I forgot to give you the correct query!

Instead of: `/terrain`

Can you change it to: `/guardian`

2022-10-14 13:37 UTC, Neoplatonist commented on libs/redux/userGuardians/api.ts
> +const userGuardiansApi = clientApi.injectEndpoints({
Just to keep all redux APIs in the same naming convention.

Can you change `userGuardiansApi` to `UserGuardiansAPI`?

2022-10-14 13:37 UTC, Neoplatonist commented on libs/redux/userGuardians/api.ts
> +export default userGuardiansApi;
Just to keep all redux APIs in the same naming convention.

Can you change `userGuardiansApi` to `UserGuardiansAPI`?

2022-10-14 13:42 UTC, Neoplatonist commented on libs/redux/clientApi.ts
> +  tagTypes: ['TerrainsApi', 'userGuardiansApi', 'UserApi'],
Should be `UserGuardiansApi`, capitalized like the rest

2022-10-14 13:44 UTC, Neoplatonist commented on libs/redux/userGuardians/api.ts
> +      providesTags: ['userGuardiansApi'],
This providesTags should be capitalized as well `UserGuardiansApi`.

2022-10-14 13:45 UTC, Neoplatonist requested changes
Overall the PR looks great! There are just some style inconsistencies. If it helps just compare the style of the `terrains/api` to `userGuardians/api`

2022-10-15 13:14 UTC, TofuSupreme commented
I have made corrections to the naming convention as requested above.

2022-10-15 21:35 UTC, merged